apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: platform-dev
  labels:
    app: platform-app
spec:
  selector:
    app: platform-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP