apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: platform-app
  namespaceSelector:
    matchNames:
      - platform-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s