{
 "title": "Cluster Memory",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n1 - (\nnode_memory_MemAvailable_bytes\n/\nnode_memory_MemTotal_bytes\n)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nnode_memory_MemTotal_bytes\n-\nnode_memory_MemAvailable_bytes\n)\n/\n1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}