{
 "title": "Cluster Availability",
 "description": "Dashboard para monitoramento da disponibilidade do cluster Kubernetes.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}