apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'azurecloudviana@gmail.com'
      smtp_auth_username: 'azurecloudviana@gmail.com'
      smtp_auth_password: 'vnhd qsck brqm azab'

    route:
      receiver: 'email-alert'

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'azurecloudviana@gmail.com'
            send_resolved: true
