apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: platform-dev
  labels:
    app: platform-app   # ← ESSA LABEL PRECISA EXISTIR
spec:
  selector:
    app: platform-app
  ports:
    - name: http        # ← TEM QUE SER ESSE NOME
      port: 80
      targetPort: 8000