apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-app
  namespace: platform-dev
  labels:
    release: monitoring   # ← CRÍTICO
spec:
  selector:
    matchLabels:
      app: platform-app   # ← TEM QUE BATER COM O SERVICE
  namespaceSelector:
    matchNames:
      - platform-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s