name: CI - Kubernetes Observability Platform

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker build -t platform-app ./app

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4

      - name: Validar manifests Kubernetes
        run: |
          find k8s -name "*.yaml" -o -name "*.yml"

      - name: Validar Kustomize
        run: |
          kubectl kustomize k8s/overlays/dev > /dev/null
