name: CI - Kubernetes Platform App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem
        run: docker build -t platform-app ./app

      - name: Validar YAML Kubernetes
        run: |
          kubectl apply --dry-run=client -f k8s/